services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Santiago
      - CLI_ARGS= #optional
    volumes:
      - ./config:/config
      - /path/to/data/docker_backup:/backups
      - /path/to/data/Docker:/source
    ports:
      - 1019:8200
    restart: always
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.1
        order: start-first
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
      endpoint_mode: vip
networks: {}
