services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Santiago
      - CLI_ARGS= #optional
    volumes:
      - ./config:/config
      - /path/to/data/docker_backup:/backups
      - /path/to/data/Docker:/source
    ports:
      - 1019:8200
    restart: always
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role == worker
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
networks: {}
